Repository DEBDEEP-BANERJ2E/StellarX, pull requests merged in 2025-03, with the labels that each got.

#5 Added hover effect in social icons
  assets/css/style1.css
Labels: apertre2.0, Easy

#23 added hover effect in sign-in and sign-up buttons
  frontend_firebase/public/assets/css/style1.css
Labels: apertre2.0, Easy

#27 added sign-up validation
  frontend_firebase/public/assets/css/style1.css
  frontend_firebase/public/login.js
  frontend_firebase/public/login_firebase.html
Labels: apertre2.0, hard

#29 Made login page responsive
  frontend_firebase/public/assets/css/style1.css
  frontend_firebase/public/login.html
Labels: apertre2.0, medium

#35 Login UI Enhanced
  frontend_firebase/public/assets/css/style1.css
  frontend_firebase/public/assets/js/main.js
  frontend_firebase/public/login.js
  frontend_firebase/public/login_firebase.html
Labels: apertre2.0, medium

#33 Update css
  frontend/public/assets/css/style.css
  frontend/public/assets/css/style1.css
  frontend/public/assets/css/style2.css
  frontend/public/assets/css/styles.css
Labels: apertre2.0, Easy

#31 Make next_index.html page responsive
  frontend_firebase/public/assets/img/close_nav.png
  frontend_firebase/public/assets/img/open_nav.png
  frontend_firebase/public/next_index.html
Labels: apertre2.0, medium
